[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.4"

[[constraint]]
  branch = "master"
  name = "github.com/juju/errors"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"
